debug=true

http_bind_addr="0.0.0.0:30112"

levels=[100, 1000, 10000, 50000]

base_online_numbers=[300, 60, 180, 30, 90, 180, 270, 450, 240, 600, 510, 480, 690, 540, 450, 570, 660, 360, 570, 600, 630, 930, 1050, 540]

operate_timeout_second=20

endpoint_describe_user="http://0.0.0.0:30113/public/fingerplay/account/v1/describe/user"
endpoint_transfer="http://0.0.0.0:30113/private/fingerplay/account/v1/transfer"
endpoint_login_ai="http://0.0.0.0:30113/private/fingerplay/account/v1/login/ai"

robot_uid=1000
robot_fb_open_id="x"
robot_lifetime_second=200

mongo_server_addrs="0.0.0.0:30600"

mongo_db="fingerplay"

[[fake_ranking]]
avatar="https://www-staging.bigplayer.co/activity/avatars/1.jpg"
nickname="John Lock"
win_amount=121828.0

[[fake_ranking]]
avatar="https://www-staging.bigplayer.co/activity/avatars/2.jpg"
nickname="Oliver Hank"
win_amount=113213.0

[[fake_ranking]]
avatar="https://www-staging.bigplayer.co/activity/avatars/3.jpg"
nickname="Muhammad Woold"
win_amount=110112.0

[[fake_ranking]]
avatar="https://www-staging.bigplayer.co/activity/avatars/4.jpg"
nickname="Noah Gover"
win_amount=100122.0

[[fake_ranking]]
avatar="https://www-staging.bigplayer.co/activity/avatars/5.jpg"
nickname="Jack Dannis"
win_amount=90012.0

[[fake_ranking]]
avatar="https://www-staging.bigplayer.co/activity/avatars/6.jpg"
nickname="Charlie Junk"
win_amount=87003.0

[[fake_ranking]]
avatar="https://www-staging.bigplayer.co/activity/avatars/7.jpg"
nickname="Jacob Volf"
win_amount=85011.0

[[fake_ranking]]
avatar="https://www-staging.bigplayer.co/activity/avatars/8.jpg"
nickname="George Look"
win_amount=82001.0

[[fake_ranking]]
avatar="https://www-staging.bigplayer.co/activity/avatars/9.jpg"
nickname="Ethan Goole"
win_amount=81351.0

[[fake_ranking]]
avatar="https://www-staging.bigplayer.co/activity/avatars/10.jpg"
nickname="Henry Huffle"
win_amount=80129.0

## robot avatar
[[robot]]
avatar="https://www-staging.bigplayer.co/activity/avatars/1.jpg"
nickname="Abigail Joseph"

[[robot]]
avatar="https://www-staging.bigplayer.co/activity/avatars/2.jpg"
nickname="Adams Katherine Omotayo"

[[robot]]
avatar="https://www-staging.bigplayer.co/activity/avatars/3.jpg"
nickname="AddiQueen Palmer"

[[robot]]
avatar="https://www-staging.bigplayer.co/activity/avatars/4.jpg"
nickname="Adebola Favour Odiaka"

[[robot]]
avatar="https://www-staging.bigplayer.co/activity/avatars/5.jpg"
nickname="Ahmed Abdulramon"

[[robot]]
avatar="https://www-staging.bigplayer.co/activity/avatars/6.jpg"
nickname="Ahmed Kipozy"

[[robot]]
avatar="https://www-staging.bigplayer.co/activity/avatars/7.jpg"
nickname="AJ"

[[robot]]
avatar="https://www-staging.bigplayer.co/activity/avatars/8.jpg"
nickname="Akeem Lumidéé Bolaji"

[[robot]]
avatar="https://www-staging.bigplayer.co/activity/avatars/9.jpg"
nickname="Akillo"

[[robot]]
avatar="https://www-staging.bigplayer.co/activity/avatars/10.jpg"
nickname="Akosuaakyaa Essel"

[[robot]]
avatar="https://www-staging.bigplayer.co/activity/avatars/11.jpg"
nickname="Alajiki Bamise Farotimi"

[[robot]]
avatar="https://www-staging.bigplayer.co/activity/avatars/12.jpg"
nickname="Andy Tohbad"

[[robot]]
avatar="https://www-staging.bigplayer.co/activity/avatars/13.jpg"
nickname="Annie godwin"

[[robot]]
avatar="https://www-staging.bigplayer.co/activity/avatars/14.jpg"
nickname="apallo"

[[robot]]

avatar="https://www-staging.bigplayer.co/activity/avatars/15.jpg"
nickname="Ariel Latoya Dakbai"

[[robot]]

avatar="https://www-staging.bigplayer.co/activity/avatars/16.jpg"
nickname="Ariza Setiaputra"

[[robot]]

avatar="https://www-staging.bigplayer.co/activity/avatars/17.jpg"
nickname="Awudu Barkisu"

[[robot]]

avatar="https://www-staging.bigplayer.co/activity/avatars/18.jpg"
nickname="Balla Diaby"

[[robot]]

avatar="https://www-staging.bigplayer.co/activity/avatars/19.jpg"
nickname="Bellah"

[[robot]]

avatar="https://www-staging.bigplayer.co/activity/avatars/20.jpg"
nickname="Bemous Kara"

[[robot]]
avatar="https://www-staging.bigplayer.co/activity/avatars/21.jpg"

nickname="Benflow Moses Kure"

[[robot]]

avatar="https://www-staging.bigplayer.co/activity/avatars/22.jpg"
nickname="Bernard Radido"

[[robot]]

avatar="https://www-staging.bigplayer.co/activity/avatars/23.jpg"
nickname="Bethy Bonnie"

[[robot]]

avatar="https://www-staging.bigplayer.co/activity/avatars/24.jpg"
nickname="Bonjarito Wambua"

[[robot]]

avatar="https://www-staging.bigplayer.co/activity/avatars/25.jpg"
nickname="brianmusyoki"

[[robot]]

avatar="https://www-staging.bigplayer.co/activity/avatars/26.jpg"
nickname="cherry berries"

[[robot]]

avatar="https://www-staging.bigplayer.co/activity/avatars/27.jpg"
nickname="Chinguiz Gucci Le Tchee"

[[robot]]

avatar="https://www-staging.bigplayer.co/activity/avatars/28.jpg"
nickname="Chris the billionaire"

[[robot]]

avatar="https://www-staging.bigplayer.co/activity/avatars/29.jpg"
nickname="David Akorli Mony"

[[robot]]

avatar="https://www-staging.bigplayer.co/activity/avatars/30.jpg"
nickname="David Mwakala"

[[robot]]

avatar="https://www-staging.bigplayer.co/activity/avatars/31.jpg"
nickname="david p salmz"

[[robot]]

avatar="https://www-staging.bigplayer.co/activity/avatars/32.jpg"
nickname="Denilson Chabaga"

[[robot]]

avatar="https://www-staging.bigplayer.co/activity/avatars/33.jpg"
nickname="Dennis Richuni"

[[robot]]

avatar="https://www-staging.bigplayer.co/activity/avatars/34.jpg"
nickname="Destiny Junior"

[[robot]]

avatar="https://www-staging.bigplayer.co/activity/avatars/35.jpg"
nickname="Dherbby Ajayi"

[[robot]]

avatar="https://www-staging.bigplayer.co/activity/avatars/36.jpg"
nickname="Durojaiye Motunrayo"

[[robot]]

avatar="https://www-staging.bigplayer.co/activity/avatars/37.jpg"
nickname="Edm Kudjo Dansu"

[[robot]]

avatar="https://www-staging.bigplayer.co/activity/avatars/38.jpg"
nickname="Efe Emeserhire Rihan"

[[robot]]

avatar="https://www-staging.bigplayer.co/activity/avatars/39.jpg"
nickname="Ericoh Muchui"

[[robot]]

avatar="https://www-staging.bigplayer.co/activity/avatars/40.jpg"
nickname="Evance Tilya"

[[robot]]

avatar="https://www-staging.bigplayer.co/activity/avatars/41.jpg"
nickname="Ewurabena Cherylipz"

[[robot]]

avatar="https://www-staging.bigplayer.co/activity/avatars/42.jpg"
nickname="Fa Rova"

[[robot]]

avatar="https://www-staging.bigplayer.co/activity/avatars/43.jpg"
nickname="fablous"

[[robot]]

avatar="https://www-staging.bigplayer.co/activity/avatars/44.jpg"
nickname="Feme Enoch"

[[robot]]

avatar="https://www-staging.bigplayer.co/activity/avatars/45.jpg"
nickname="Fiona Danka Donkor"

[[robot]]

avatar="https://www-staging.bigplayer.co/activity/avatars/46.jpg"
nickname="Flores Danny Daniel"

[[robot]]

avatar="https://www-staging.bigplayer.co/activity/avatars/47.jpg"
nickname="Franc Amache"

[[robot]]

avatar="https://www-staging.bigplayer.co/activity/avatars/48.jpg"
nickname="Friday Mark"

[[robot]]

avatar="https://www-staging.bigplayer.co/activity/avatars/49.jpg"
nickname="gido"

[[robot]]

avatar="https://www-staging.bigplayer.co/activity/avatars/50.jpg"
nickname="Gukiina Paul"

[[robot]]

avatar="https://www-staging.bigplayer.co/activity/avatars/51.jpg"
nickname="HajiaAyisha Shuaib"

[[robot]]

avatar="https://www-staging.bigplayer.co/activity/avatars/52.jpg"
nickname="Hajj Hamid"

[[robot]]

avatar="https://www-staging.bigplayer.co/activity/avatars/53.jpg"
nickname="Henry Hinamundi"

[[robot]]

avatar="https://www-staging.bigplayer.co/activity/avatars/54.jpg"
nickname="Junaid Oluwaseun"

[[robot]]

avatar="https://www-staging.bigplayer.co/activity/avatars/55.jpg"
nickname="K-x"

[[robot]]

avatar="https://www-staging.bigplayer.co/activity/avatars/56.jpg"
nickname="Kaptain_AL"

[[robot]]

avatar="https://www-staging.bigplayer.co/activity/avatars/57.jpg"
nickname="Kate Esi Tawiah"

[[robot]]

avatar="https://www-staging.bigplayer.co/activity/avatars/58.jpg"
nickname="Kefa"

[[robot]]

avatar="https://www-staging.bigplayer.co/activity/avatars/59.jpg"
nickname="KELA"

[[robot]]

avatar="https://www-staging.bigplayer.co/activity/avatars/60.jpg"
nickname="Ken Koxs"

[[robot]]

avatar="https://www-staging.bigplayer.co/activity/avatars/61.jpg"
nickname="Kenneth AJ Elisha"

[[robot]]

avatar="https://www-staging.bigplayer.co/activity/avatars/62.jpg"
nickname="king72176"

[[robot]]

avatar="https://www-staging.bigplayer.co/activity/avatars/63.jpg"
nickname="kudamok"

[[robot]]

avatar="https://www-staging.bigplayer.co/activity/avatars/64.jpg"
nickname="Leah Jepkemoi"

[[robot]]

avatar="https://www-staging.bigplayer.co/activity/avatars/65.jpg"
nickname="Loise Wambui"

[[robot]]

avatar="https://www-staging.bigplayer.co/activity/avatars/66.jpg"
nickname="luphle3cious"

[[robot]]

avatar="https://www-staging.bigplayer.co/activity/avatars/67.jpg"
nickname="Mafya Mbishi"

[[robot]]

avatar="https://www-staging.bigplayer.co/activity/avatars/68.jpg"
nickname="Manou Leprince"

[[robot]]

avatar="https://www-staging.bigplayer.co/activity/avatars/69.jpg"
nickname="Manuel Wad"

[[robot]]

avatar="https://www-staging.bigplayer.co/activity/avatars/70.jpg"
nickname="Mary Keysh"

[[robot]]

avatar="https://www-staging.bigplayer.co/activity/avatars/71.jpg"
nickname="Maxy Morgan Oloo"

[[robot]]

avatar="https://www-staging.bigplayer.co/activity/avatars/72.jpg"
nickname="Mirah Bae"

[[robot]]

avatar="https://www-staging.bigplayer.co/activity/avatars/73.jpg"
nickname="Moses Nuhu Chagwa"

[[robot]]

avatar="https://www-staging.bigplayer.co/activity/avatars/74.jpg"
nickname="moskie"

[[robot]]

avatar="https://www-staging.bigplayer.co/activity/avatars/75.jpg"
nickname="Mudashir Aliyu"

[[robot]]

avatar="https://www-staging.bigplayer.co/activity/avatars/76.jpg"
nickname="Nancy Ampofowaa"

[[robot]]

avatar="https://www-staging.bigplayer.co/activity/avatars/77.jpg"
nickname="Naomie Gbarjolo"

[[robot]]

avatar="https://www-staging.bigplayer.co/activity/avatars/78.jpg"
nickname="Ndine Nkotsi"

[[robot]]
avatar="https://www-staging.bigplayer.co/activity/avatars/79.jpg"

nickname="Neyoo Olawale Balogun"

[[robot]]

avatar="https://www-staging.bigplayer.co/activity/avatars/80.jpg"
nickname="Nharnah Adjoa Bruce"

[[robot]]

avatar="https://www-staging.bigplayer.co/activity/avatars/81.jpg"
nickname="nicky lasty"

[[robot]]

avatar="https://www-staging.bigplayer.co/activity/avatars/82.jpg"
nickname="Nina Ahibo"

[[robot]]

avatar="https://www-staging.bigplayer.co/activity/avatars/83.jpg"
nickname="Novie Noer Chasanah"

[[robot]]

avatar="https://www-staging.bigplayer.co/activity/avatars/84.jpg"
nickname="Olivia Cudjoea"

[[robot]]

avatar="https://www-staging.bigplayer.co/activity/avatars/85.jpg"
nickname="oshua Charles"

[[robot]]

avatar="https://www-staging.bigplayer.co/activity/avatars/86.jpg"
nickname="Peacemaker"

[[robot]]

avatar="https://www-staging.bigplayer.co/activity/avatars/87.jpg"
nickname="Pretty Jumash"

[[robot]]

avatar="https://www-staging.bigplayer.co/activity/avatars/88.jpg"
nickname="ramanna"

[[robot]]

avatar="https://www-staging.bigplayer.co/activity/avatars/89.jpg"
nickname="Reny Donald S"

[[robot]]

avatar="https://www-staging.bigplayer.co/activity/avatars/90.jpg"
nickname="Reny Donald"

[[robot]]

avatar="https://www-staging.bigplayer.co/activity/avatars/91.jpg"
nickname="Sandra"

[[robot]]

avatar="https://www-staging.bigplayer.co/activity/avatars/92.jpg"
nickname="Seddy M Joshua"

[[robot]]

avatar="https://www-staging.bigplayer.co/activity/avatars/93.jpg"
nickname="shy-bhuy"

[[robot]]

avatar="https://www-staging.bigplayer.co/activity/avatars/94.jpg"
nickname="Simon Jay"

[[robot]]

avatar="https://www-staging.bigplayer.co/activity/avatars/95.jpg"
nickname="Sky"

[[robot]]

avatar="https://www-staging.bigplayer.co/activity/avatars/96.jpg"
nickname="skyyebaby"

[[robot]]

avatar="https://www-staging.bigplayer.co/activity/avatars/97.jpg"
nickname="Success Ekelemchi"

[[robot]]

avatar="https://www-staging.bigplayer.co/activity/avatars/98.jpg"
nickname="Sweetie Dor Hector"

[[robot]]

avatar="https://www-staging.bigplayer.co/activity/avatars/99.jpg"
nickname="Teresa Ngendo"

[[robot]]

avatar="https://www-staging.bigplayer.co/activity/avatars/100.jpg"
nickname="thundhexy"

[[robot]]

avatar="https://www-staging.bigplayer.co/activity/avatars/101.jpg"
nickname="Twina Matsiko Ivan"

[[robot]]

avatar="https://www-staging.bigplayer.co/activity/avatars/102.jpg"
nickname="Ubong Peter"

[[robot]]

avatar="https://www-staging.bigplayer.co/activity/avatars/103.jpg"
nickname="Ugochukwu Mokezie"

[[robot]]

avatar="https://www-staging.bigplayer.co/activity/avatars/104.jpg"
nickname="viiv princess"

[[robot]]

avatar="https://www-staging.bigplayer.co/activity/avatars/105.jpg"
nickname="Waweru Winnie"

[[robot]]

avatar="https://www-staging.bigplayer.co/activity/avatars/106.jpg"
nickname="young Stive"

[[robot]]

avatar="https://www-staging.bigplayer.co/activity/avatars/107.jpg"
nickname="YungBaller Elazey"
